apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: local-pvc-backup
spec:
  selector:
    matchLabels:
      app: local-pvc-backup
  template:
    metadata:
      labels:
        app: local-pvc-backup
    spec:
      serviceAccountName: local-pvc-backup
      containers:
        - name: backup
          image: ghcr.io/monlor/local-pvc-backup:main
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # S3 Configuration
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: local-pvc-backup
                  key: S3_ENDPOINT
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: local-pvc-backup
                  key: S3_BUCKET
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: local-pvc-backup
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: local-pvc-backup
                  key: S3_SECRET_KEY
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: local-pvc-backup
                  key: S3_REGION
            # Restic Configuration
            - name: RESTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: local-pvc-backup
                  key: RESTIC_PASSWORD
            # Backup Configuration from ConfigMap
            - name: BACKUP_STORAGE_PATH
              valueFrom:
                configMapKeyRef:
                  name: local-pvc-backup
                  key: BACKUP_STORAGE_PATH
            - name: BACKUP_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: local-pvc-backup
                  key: BACKUP_LOG_LEVEL
            - name: BACKUP_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: local-pvc-backup
                  key: BACKUP_INTERVAL
            - name: BACKUP_RETENTION
              valueFrom:
                configMapKeyRef:
                  name: local-pvc-backup
                  key: BACKUP_RETENTION
            - name: S3_PATH
              valueFrom:
                configMapKeyRef:
                  name: local-pvc-backup
                  key: S3_PATH
            - name: RESTIC_CACHE_PATH
              valueFrom:
                configMapKeyRef:
                  name: local-pvc-backup
                  key: RESTIC_CACHE_PATH
          volumeMounts:
            - name: storage
              mountPath: /data
            - name: cache
              mountPath: /var/cache/restic
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: storage
          hostPath:
            path: /var/lib/rancher/k3s/storage
            type: Directory
        - name: cache
          hostPath:
            path: /var/lib/local-pvc-backup/cache
            type: DirectoryOrCreate 