apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - daemonset.yaml
  - rbac.yaml

commonLabels:
  app.kubernetes.io/name: local-pvc-backup
  app.kubernetes.io/part-of: backup

secretGenerator:
  - name: local-pvc-backup
    literals:
      - s3-endpoint=http://minio.default.svc.cluster.local:9000
      - s3-bucket=backup
      - s3-access-key=minioadmin
      - s3-secret-key=minioadmin
      - s3-region=us-east-1
      - s3-path=backups
      - restic-password=your-restic-password