apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - rbac.yaml
  - daemonset.yaml

commonLabels:
  app.kubernetes.io/name: local-pvc-backup
  app.kubernetes.io/part-of: backup

configMapGenerator:
  - name: local-pvc-backup
    literals:
      - BACKUP_STORAGE_PATH=/data
      - BACKUP_LOG_LEVEL=info
      - BACKUP_INTERVAL=1h
      - BACKUP_RETENTION=14d
      - S3_PATH=
      - RESTIC_CACHE_DIR=/var/cache/restic

secretGenerator:
  - name: local-pvc-backup
    literals:
      - S3_ENDPOINT=
      - S3_BUCKET=
      - S3_ACCESS_KEY=
      - S3_SECRET_KEY=
      - S3_REGION=
      - RESTIC_PASSWORD=