name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Add permissions configuration at the workflow level
permissions:
  contents: read
  packages: write
  id-token: write    # Needed for signing the images with cosign

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build-amd64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-amd64-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-amd64-

      - name: Build and push AMD64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: false  # Don't push to registry
          load: true   # Load into docker daemon
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:amd64-${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      
      - name: Save AMD64 image
        run: |
          mkdir -p /tmp/images
          docker save ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:amd64-${{ github.sha }} -o /tmp/images/amd64-image.tar
      
      - name: Upload AMD64 image artifact
        uses: actions/upload-artifact@v4
        with:
          name: amd64-image
          path: /tmp/images/amd64-image.tar
          retention-days: 1  # Only keep for 1 day

  build-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-arm64-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-arm64-

      - name: Build and push ARM64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: false  # Don't push to registry
          load: true   # Load into docker daemon
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:arm64-${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      
      - name: Save ARM64 image
        run: |
          mkdir -p /tmp/images
          docker save ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:arm64-${{ github.sha }} -o /tmp/images/arm64-image.tar
      
      - name: Upload ARM64 image artifact
        uses: actions/upload-artifact@v4
        with:
          name: arm64-image
          path: /tmp/images/arm64-image.tar
          retention-days: 1  # Only keep for 1 day

  merge-and-cleanup:
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Download AMD64 image
        uses: actions/download-artifact@v4
        with:
          name: amd64-image
          path: /tmp/images

      - name: Download ARM64 image
        uses: actions/download-artifact@v4
        with:
          name: arm64-image
          path: /tmp/images

      - name: Load images
        run: |
          docker load -i /tmp/images/amd64-image.tar
          docker load -i /tmp/images/arm64-image.tar

      - name: Create and push multi-arch manifest
        run: |
          # Create manifest list and push it
          docker manifest create ${{ steps.meta.outputs.tags }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:amd64-${{ github.sha }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:arm64-${{ github.sha }}
    
          # Push the manifest list
          docker manifest push ${{ steps.meta.outputs.tags }}

      # Sign the resulting Docker image
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.0'

      - name: Sign the published Docker image
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          cosign sign --yes ${TAGS}
